/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hwjoo_ndkproject_TestNDK */

#ifndef _Included_com_hwjoo_ndkproject_TestNDK
#define _Included_com_hwjoo_ndkproject_TestNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hwjoo_ndkproject_TestNDK
 * Method:    getNDKString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hwjoo_ndkproject_TestNDK_getNDKString
  (JNIEnv *, jobject);

/*
 * Class:     com_hwjoo_ndkproject_TestNDK
 * Method:    sumOneHundred
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hwjoo_ndkproject_TestNDK_sumOneHundred
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
